### ISSUE TITLE
Edit employee should populate with current information

### ISSUE THREAD

**Issue by Jon-nim** [skippycrow/T3_CS2450_001#53]
When you edit emploiyee from both emplyee_list_Frame and from profile_frame, the data doesn't pre-populate in the fields. This could be confusing on the users part. Also having to put all the correct data back in seems like a pain.

**Comment by ACast1** [comment]
Fixed now except drop down menus because that would be redundant

**Comment by Jon-nim** [comment]
I went and tried to edit employee to see the changes I could make. Information still doesn't populate. Would you look into this again? Maybe this update wasn't merged branch yet.

**Comment by zacryol** [comment]
how are the drop-down menus redundant?

**Comment by ACast1** [comment]
> I went and tried to edit employee to see the changes I could make. Information still doesn't populate. Would you look into this again? Maybe this update wasn't merged branch yet.

I just tried it and I see the ID, First Name, Last name, Street, City, State, Zip, Phone, Email, Routing#, Account#, SSN, DOB, Start Date, End Date, Title, and Dept all populate with the correct information

**Comment by ACast1** [comment]
> how are the drop-down menus redundant?

I thought they were, but if you don't think so you are more than welcome to get those populated

**Comment by zacryol** [comment]
It's absolutely important
It's a field that gets saved in the database.

**Comment by zacryol** [comment]
Not populating the data for that field seems to be causing the whole thing to break when trying to save

**Comment by ACast1** [comment]
Drop down menus now populate with current information with this pull request https://github.com/skippycrow/T3_CS2450_001/pull/62
However the resave_cache() function does not seem to work as expected. It needs to be reviewed.

**Comment by zacryol** [comment]
> However the resave_cache() function does not seem to work as expected just yet.

Fixed with #63

**Comment by ACast1** [comment]
> > However the resave_cache() function does not seem to work as expected just yet.
> 
> Fixed with #63

Am I good to merge to main now?

**Comment by zacryol** [comment]
I left some review comments on that PR https://github.com/skippycrow/T3_CS2450_001/pull/62#discussion_r767903537
It looks like it should work (haven't tested it myself), but I left a recommendation for making it cleaner.

**Comment by ACast1** [comment]
> I left some review comments on that PR [#62 (comment)](https://github.com/skippycrow/T3_CS2450_001/pull/62#discussion_r767903537) It looks like it should work (haven't tested it myself), but I left a recommendation for making it cleaner.

Review the response I made to those comments. It is working as expected. After updating the password I close the app and try the new password and it works so I am going to merge the changes I made to EditEmployee and AddEmployee which will also fix the data population for drop down menus.
